#!/usr/bin/python3
"""File Storage implementation."""

import json
from models.engine.file_storage import FileStorage


class HBNBCommand:
        """Command line interpreter for the AirBnB clone project."""

            prompt = "(hbnb) "
                file_storage = FileStorage()

                    def do_EOF(self, arg):
                                """Exit the console gracefully."""
                                        print()
                                                return True

                                                def do_quit(self, arg):
                                                            """Quit command to exit the program."""
                                                                    return True

                                                                    def emptyline(self):
                                                                                """Do nothing on empty input."""
                                                                                        pass

                                                                                        def default(self, line):
                                                                                                    """Handle default commands."""
                                                                                                            if "." in line:
                                                                                                                            parts = line.split(".")
                                                                                                                                        cmd = parts[1].split("(")[0]
                                                                                                                                                    args = parts[1].split("(")[1].split(")")[0].split(",")
                                                                                                                                                                if cmd == "all":
                                                                                                                                                                                    print(self.file_storage.all())
                                                                                                                                                                                                elif cmd == "count":
                                                                                                                                                                                                                    print(sum(1 for _ in self.file_storage.all().values()))
                                                                                                                                                                                                                                elif cmd == "show":
                                                                                                                                                                                                                                                    if len(args) < 2:
                                                                                                                                                                                                                                                                            print("** instance id missing **")
                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                            obj_key = "{}.{}".format(args[0], args[1][1:-1])
                                                                                                                                                                                                                                                                                                                            objs = self.file_storage.all()
                                                                                                                                                                                                                                                                                                                                            if obj_key in objs:
                                                                                                                                                                                                                                                                                                                                                                    print(objs[obj_key])
                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                            print("** no instance found **")
                                                                                                                                                                                                                                                                                                                                                                                                                        elif cmd == "destroy":
                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(args) < 2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("** instance id missing **")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    obj_key = "{}.{}".format(args[0], args[1][1:-1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    objs = self.file_storage.all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if obj_key in objs:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            del objs[obj_key]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.file_storage.save()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("** no instance found **")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif cmd == "update":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if len(args) < 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("** instance id missing **")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                obj_key = "{}.{}".format(args[0], args[1][1:-1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                objs = self.file_storage.all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if obj_key not in objs:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("** no instance found **")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        attr = args[2][1:-1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if len(args) < 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("** value missing **")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value = args[3][1:-1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setattr(objs[obj_key], attr, value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.file_storage.save()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("*** Unknown syntax: {}".format(line))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("*** Unknown syntax: {}".format(line))


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                HBNBCommand().cmdloop()

